#!/usr/bin/perl
use strict;
use warnings;
use utf8;
use 5.10.0;
use Data::Dumper;
use Readonly;
use HTML::TreeBuilder::XPath;
use HTML::TreeBuilder::LibXML;
use HTML::Entities;
use LWP::ConnCache; 
use LWP::UserAgent;
use LWP::Protocol::Net::Curl; #net thing to try for performance
use CGI::Fast;
use Encode;
use POSIX qw(strftime);

binmode STDOUT, 'utf8';
binmode STDIN, 'utf8';

HTML::TreeBuilder::LibXML->replace_original();

Readonly my $BASEURL => 'https://twitter.com';
my $browser = LWP::UserAgent->new;
$browser->conn_cache(LWP::ConnCache->new(5));
$browser->timeout(2);


while (my $q = CGI::Fast->new) {
#    err("Over capacity.  Try running your own instance - code on github.",404);
#    next;
        my @ps = $q->param; 
        my $bad_param=0;
        for(@ps) {
          unless ($_=~/^(fetch|replies|user)$/) {
            err("Bad parameters. Naughty.",404); 
            $bad_param++;
            last;
          }
        } 
        next if $bad_param;

	my $user = $q->param('user') || 'ciderpunx';

	$user = lc $user;
        if($user =~ '^#') {
		err("That was an hashtag, TwitRSS.me only supports users!",404); 
                next;
	}
	$user=~s/(@|\s)//g;
	$user=~s/%40//g;

	my $max_age=1800;

	my $replies = $q->param('replies') || 0;
	if ($replies && lc($replies) ne 'on') {
          err("Bad parameters. Naughty.",404); 
          $bad_param++;
          next;
	}

	my $url = "$BASEURL/$user";
	$url .= "/with_replies" if $replies;

	my $response = $browser->get($url);
	unless ($response->is_success) {
		err('Can&#8217;t screenscrape Twitter',404);
		next;
	}
	my $content = $response->content;

	my @items;

	my $tree= HTML::TreeBuilder::XPath->new;
	$tree->parse($content);
  my $tweets = $tree->findnodes( '//li' . class_contains('js-stream-item')); # new version 2015-06-02
  if ($tweets) {
    for my $li (@$tweets) {    
      my $tweet = $li->findnodes('./div' 
                                  . class_contains("js-stream-tweet") 
                                )->[0]
      ;
      next unless $tweet;
      my $header = $tweet->findnodes('./div/div' 
                                     . class_contains("stream-item-header") 
                                     . "/a" 
                                     . class_contains("js-action-profile"))->[0];
      my $bd   = $tweet->findnodes( './div/p' 
                                     . class_contains("js-tweet-text")
                                     . "")->[0];
      my $body = "<![CDATA[" . encode_entities($bd->as_HTML,'^\n\x20-\x25\x27-\x7e"') . "]]>";
      $body=~s{&amp;(\w+);}{&$1;}gi;
      $body=~s{target="_blank"}{}gi;
      my $avatar = $header->findvalue('./img' . class_contains("avatar") . "/\@src"); 
      my $fullname = $header->findvalue('./strong' . class_contains("fullname"));
      my $username = $header->findvalue('./span' . class_contains("username"));
      $username =~ s{<[^>]+>}{}g;
      $username =~ s{^\s+}{};
      $username =~ s{\s+$}{};
      my $title = "<![CDATA[$username: " . encode_entities(decode_entities($bd->as_text), '^\n\x20-\x25\x27-\x7e') ."]]>";
      #$title =~ s{A\[}{A\[$username: }; # yuk, prepend username to title
      $title=~s{&nbsp;}{}gi;
      my $uri = $BASEURL . $tweet->findvalue('@data-permalink-path');  
      my $timestamp = $tweet->findnodes('./div/div'
                      . class_contains("stream-item-header")
                      . '/small/a' 
                      . class_contains("tweet-timestamp"))->[0]->findvalue('./span/@data-time'
      );  

      my $pub_date = strftime("%a, %d %b %Y %H:%M:%S %z", localtime($timestamp));

      push @items, {
        username => $username,
        fullname => $fullname,
        link => $uri,
        guid => $uri,
        title => $title,
        description => $body,
        timestamp => $timestamp,
        pubDate => $pub_date,
      }
    }
	}
  else {
    $tree->delete; 
    err("Can't gather tweets for that user",404);
    next;
  }
  $tree->delete; 

	# now print as an rss feed, with header
print<<ENDHEAD
Content-type: application/rss+xml
Cache-control: max-age=$max_age

<?xml version="1.0" encoding="UTF-8"?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:georss="http://www.georss.org/georss" xmlns:twitter="http://api.twitter.com" version="2.0">
  <channel>
    <title>Twitter Search / $user </title>
    <link>http://twitter.com/$user</link>
    <description>Twitter feed for: $user. Generated by TwitRSS.me</description>
    <language>en-us</language>
    <ttl>40</ttl>
ENDHEAD
;

for (@items) {
  print<<ENDITEM
    <item>
      <title>$_->{title}</title>
      <description>$_->{description}</description>
      <pubDate>$_->{pubDate}</pubDate>
      <guid>$_->{guid}</guid>
      <link>$_->{link}</link>
      <twitter:source/>
      <twitter:place/>
    </item>
ENDITEM
;
}

print<<ENDRSS
  </channel>
</rss>      
ENDRSS
;
}

sub class_contains {
  my $classname = shift;
  "[contains(concat(' ',normalize-space(\@class),' '),' $classname ')]";
}

sub err {
	my ($msg,$status) = (shift,shift);
	print<<ENDHEAD
Content-type: text/html
Status: $status
Cache-control: max-age=86400
Refresh: 10; url=http://twitrss.me

<html><head></head><body><h2>ERR: $msg</h2><p>Redirecting you back to <a href="http://twitrss.me">TwitRSS.me</a> in a few seconds. You might have spelled the username wrong or something</p></body></html>
ENDHEAD
;
}
